package io.swagger.petstore.asserts;

import io.swagger.petstore.models.Pet;

/**
 * {@link Pet} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractPetAssert} instead.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public class PetAssert extends AbstractPetAssert<PetAssert, Pet> {

  /**
   * Creates a new <code>{@link PetAssert}</code> to make assertions on actual Pet.
   * @param actual the Pet we want to make assertions on.
   */
  public PetAssert(Pet actual) {
    super(actual, PetAssert.class);
  }

  /**
   * An entry point for PetAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myPet)</code> and get specific assertion with code completion.
   * @param actual the Pet we want to make assertions on.
   * @return a new <code>{@link PetAssert}</code>
   */
  @org.assertj.core.util.CheckReturnValue
  public static PetAssert assertThat(Pet actual) {
    return new PetAssert(actual);
  }
}
